from app.exception.errors import (
    AppError,
    AttemptNotFoundError,
    ConfigurationError,
    CourseNotFoundError,
    DuplicateTextbookError,
    EmptyDocumentError,
    FileTooLargeError,
    GroupNotFoundError,
    InvalidSubmissionError,
    LlmError,
    MaterialNotFoundError,
    NoMaterialError,
    QuizNotFoundError,
    TextbookNotFoundError,
    UnsupportedFileTypeError,
)
from app.exception.handlers import register_exception_handlers

__all__ = [
    "AppError",
    "AttemptNotFoundError",
    "ConfigurationError",
    "CourseNotFoundError",
    "DuplicateTextbookError",
    "EmptyDocumentError",
    "FileTooLargeError",
    "GroupNotFoundError",
    "InvalidSubmissionError",
    "LlmError",
    "MaterialNotFoundError",
    "NoMaterialError",
    "QuizNotFoundError",
    "TextbookNotFoundError",
    "UnsupportedFileTypeError",
    "register_exception_handlers",
]
